### ISSUE TITLE
Conflict with dnd5e-character-monitor

### ISSUE THREAD

**Issue by ChthonicKnight** [ZeroXNoxus/dark-mode-5e#10] opened 2024-02-08 23:04 UTC
Conflict with dnd5e-character-monitor
Seems to double up on the high contrast display of the text in the chat log.
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/21301107/e067d88a-2d7a-4507-85ef-04f4dcef4347)

**Comment by ZeroXNoxus** [comment] 2024-02-09 11:24
Working as intended on 3.0.0+. Colors don't seem to apply in the newer release:
![image](https://github.com/ZeroXNoxus/dark-mode-5e/assets/29397572/7945b5de-ee1d-4245-9ebc-f76633e84a73)

I'll exclude Character Monitor messages from Dark Mode for now. This will be resolved in the next release.

**Closed as completed** 2024-02-09 11:28 UTC
